on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install tailwindcss
        run: |
          curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
          chmod +x tailwindcss-linux-x64
          sudo mv tailwindcss-linux-x64 /usr/local/bin/tailwindcss
          tailwindcss --version

      - name: build pages
        run: |
          rustup update
          cargo run

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./pages/

  deploy:
    runs-on: ubuntu-latest

    needs: build

    permissions:
      contents: read
      id-token: write
      pages: write

    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - id: deploy
        uses: actions/deploy-pages@v4
        