on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: build pages
        run: |
          rustup --version
          cargo --version
          cargo run

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./pages/

  deploy:
    runs-on: ubuntu-latest

    needs: build

    permissions:
      contents: read
      id-token: write
      pages: write

    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - id: deploy
        uses: actions/deploy-pages@v4
        